/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 44
#define YY_END_OF_BUFFER 45
static yyconst short int yy_acclist[367] =
    {   0,
       45,   44,    1,   44,    5,   44,   36,   44,   36,   44,
       44,   36,   44,   36,   44,   44,   36,   44,   36,   44,
       36,   44,   41,   42,   44,   36,   44,   36,   44,   36,
       44,   39,   44,   39,   44,   39,   44,   39,   44,   39,
       44,   39,   44,   39,   44,   39,   44,   39,   44,   39,
       44,   39,   44,   39,   44,   39,   44,   44,   39,   44,
       39,   44,   39,   44,   39,   44,   39,   44,   39,   44,
       39,   44,   39,   44,   39,   44,   39,   44,   39,   44,
       39,   44,   39,   44,   29,   40,   31,   34,   35,    4,
       41,   42,   33,   27,   28,   26,   32,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   12,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   30,   43,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   12,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   37,    4,    4,   25,   42,   42,   38,   39,
       39,   39,   39,   39,   24,   39,   39,   39,   39,   39,
       15,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   24,   39,   39,   39,
       39,   39,   15,   39,   39,   39,   39,   39,   39,   39,
       39,    3,    4,   39,   17,   39,   39,   11,   39,   18,

       39,   23,   39,   39,   39,   13,   39,   39,   39,   39,
       39,   39,   20,   39,   39,   39,   39,   39,   17,   39,
       39,   11,   39,   18,   39,   23,   39,   39,   39,   13,
       39,   39,   39,   39,   39,   39,   20,   39,   39,    3,
       39,   22,   39,   39,   39,   39,   39,   39,   39,    8,
       39,   39,   39,   39,   22,   39,   39,   39,   39,   39,
       39,   39,    8,   39,   39,   39,   16,   39,    6,    7,
       39,   21,   39,   19,   39,    9,   39,   39,   39,   39,
       39,   16,   39,    7,   39,   21,   39,   19,   39,    9,
       39,   39,   10,   39,   39,   39,   39,   10,   39,   14,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,    2,   39,   39,   39,    2,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39
    } ;

static yyconst short int yy_accept[313] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    9,   11,   12,
       14,   16,   17,   19,   21,   23,   26,   28,   30,   32,
       34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
       54,   56,   58,   59,   61,   63,   65,   67,   69,   71,
       73,   75,   77,   79,   81,   83,   85,   86,   86,   87,
       87,   88,   88,   88,   89,   90,   91,   91,   91,   93,
       93,   94,   95,   96,   97,   98,   98,   99,  100,  101,
      102,  103,  104,  105,  106,  107,  108,  109,  111,  112,
      113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
      123,  124,  125,  126,  127,  128,  129,  130,  131,  132,

      133,  135,  136,  137,  138,  139,  140,  141,  142,  143,
      143,  144,  144,  145,  145,  146,  146,  147,  148,  148,
      149,  150,  151,  152,  153,  154,  155,  157,  158,  159,
      160,  161,  163,  164,  165,  166,  167,  168,  169,  170,
      171,  172,  173,  174,  175,  176,  177,  179,  180,  181,
      182,  183,  185,  186,  187,  188,  189,  190,  191,  192,
      192,  192,  192,  194,  195,  197,  198,  200,  202,  204,
      205,  206,  208,  209,  210,  211,  212,  213,  215,  216,
      217,  218,  219,  221,  222,  224,  226,  228,  229,  230,
      232,  233,  234,  235,  236,  237,  239,  240,  240,  241,

      242,  244,  245,  246,  246,  247,  248,  249,  250,  252,
      253,  254,  255,  257,  258,  259,  260,  261,  262,  263,
      265,  265,  266,  267,  269,  270,  272,  274,  276,  278,
      279,  280,  281,  282,  284,  286,  288,  290,  292,  292,
      293,  295,  296,  297,  298,  300,  301,  302,  303,  304,
      305,  306,  307,  308,  309,  310,  311,  312,  313,  314,
      315,  316,  317,  318,  319,  320,  321,  322,  323,  324,
      325,  327,  328,  329,  331,  332,  333,  334,  335,  336,
      337,  338,  339,  340,  341,  342,  343,  344,  345,  346,
      347,  348,  349,  350,  351,  352,  353,  354,  355,  356,

      357,  358,  359,  360,  361,  362,  363,  364,  365,  366,
      367,  367
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    8,   27,   27,   28,   27,   29,   27,
       30,   27,   31,   27,   27,   32,   33,   34,   35,   27,
       27,   27,   36,   37,   27,   27,   27,   27,   27,   27,
       38,   39,   40,   41,   42,    8,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   27,   52,   53,   54,   55,
       56,   57,   27,   58,   59,   60,   61,   62,   63,   27,
       27,   27,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    3,    4,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[349] =
    {   0,
        0,   41,  802, 1014, 1014, 1014,  777,  787,  722, 1014,
      760,  730,  749,  742,   91,   88,   56,  721,   57,  723,
       89,   91,   94,   95,   93,  100,   96,   98,  105,   97,
      103,  104,  672,  116,  150,  155,  158,  159,  164,  168,
      123,  169,  177,  180,  200,  187, 1014,  728,  715,  663,
     1014,  699,  191, 1014, 1014,  124,  704,  679,  145,  113,
     1014, 1014, 1014, 1014, 1014,  641,  670,  106,  113,  146,
      167,  176,  173,  181,  186,  194,  203,  663,  178,  207,
      212,  192,  211,  213,  214,  215, 1014, 1014,  241,  254,
      257,  264,  265,  268,  275,  276,  284,  287,  295,  296,

      303,  306,  314,  319,  322,  326,  330,  340,  344,  635,
     1014,  666,  233,  267,  289,  651, 1014,  281,  630,  629,
     1014,  323,  223,  230,  312,  293,  613,  301,  320,  236,
      331,  612,  318,  334,  336,  339,  349,  204,  350,  368,
      374,  380,  384,  393,  396,  402,  403,  409,  412,  415,
      421,  422,  428,  431,  444,  447,  453,  454,  458,  575,
      286,  366,  405,  361,  608,  427,  606,  602,  601,  356,
      354,  559,  426,  410,  408,  434,  435,  558,  440,  472,
      479,  488,  492,  498,  499,  504,  511,  512,  518,  522,
      523,  531,  534,  541,  542,  545,  550,  508,  474,  467,

      546,  475,  476,  491,  436,  491,  509,  529,  485,  554,
      563,  564,  582,  583,  586,  587,  591,  592,  595,  596,
      435,  538,  515,  445, 1014,  383,  358,  357,  279,  605,
      614,  619,  624,  635,  640,  644,  645,  648,  198,  560,
      114,  649,  653,  654,  667, 1014,  641,  672,  675,  676,
      665,  683,  686,  694,  682,  699,  702,  705,  600,  706,
      710,  713,  521,  726,  729,  732,  603,  733,  736,  737,
      111,  740,  745,  758,  759,  764,  765,  768,  769,  772,
      777,  778,  788,  791,  796,  797,  800,  801,  804,  807,
      810,  820,  823,  826,  829,  830,  833,  834,  839,  842,

      852,  853,  858,  861,  862,  865,  866,  871,  872,  884,
     1014,  902,  904,  121,  907,  911,  915,  918,  922,  925,
      928,  931,  934,  937,  940,  943,  946,  949,  952,  955,
      958,  961,  964,  967,  970,  973,  976,  979,  982,  985,
      988,  991,  994,  997, 1000, 1003, 1006, 1009
    } ;

static yyconst short int yy_def[349] =
    {   0,
      311,    1,  311,  311,  311,  311,  311,  312,  311,  311,
      311,  313,  311,  311,  311,  311,  311,  311,  311,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  311,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  311,  312,  312,  311,
      311,  311,  311,  311,  311,  316,  317,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  311,  311,  315,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  311,
      311,  311,  316,  319,  316,  317,  311,  311,  311,  311,
      311,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  318,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  311,
      319,  319,  316,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  320,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  311,  319,  314,

      314,  314,  314,  311,  314,  314,  314,  314,  314,  321,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      311,  314,  314,  314,  311,  314,  314,  314,  314,  322,
      323,  323,  323,  323,  323,  323,  323,  323,  311,  314,
      314,  323,  324,  324,  324,  311,  314,  324,  325,  325,
      314,  325,  326,  326,  314,  326,  327,  327,  314,  327,
      328,  328,  314,  328,  329,  329,  314,  329,  330,  330,
      314,  330,  331,  331,  331,  332,  332,  333,  333,  334,
      334,  335,  335,  336,  336,  337,  337,  338,  338,  339,
      339,  340,  340,  341,  341,  342,  342,  343,  343,  344,

      344,  345,  345,  346,  346,  347,  347,  348,  348,  348,
        0,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311
    } ;

static yyconst short int yy_nxt[1082] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,   11,
       12,   10,   10,   10,   13,   10,   14,   10,   15,   16,
       10,   10,   17,   18,   19,   10,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   21,   20,   10,    4,   10,
       10,   20,   20,   22,   23,   24,   25,   20,   20,   20,
       26,   20,   20,   27,   20,   20,   28,   29,   30,   20,
       20,   31,   32,   10,   33,   10,   10,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   35,   34,   61,   62,
       64,   65,   34,   34,   36,   37,   38,   39,   34,   34,
       34,   40,   34,   34,   41,   34,   34,   42,   43,   44,

       34,   34,   45,   46,   56,   58,   66,   59,   66,   57,
       66,   66,   66,   66,   66,   66,   60,   66,   88,   68,
       66,   66,   66,   66,   67,   88,  114,  119,   66,  119,
       66,   66,  120,   66,   60,   89,   71,  115,   80,  122,
       66,   75,   89,   72,   73,   77,   69,   78,   70,   74,
       76,   82,   88,   86,   79,   81,   83,   88,   85,   84,
       88,   88,   58,   66,   59,  103,   88,   66,  123,   89,
       88,   88,   66,   60,   89,   66,   66,   89,   89,   88,
       91,   66,   88,   89,   66,   66,   66,   89,   89,   88,
       66,   60,  124,   66,   66,   66,   89,   66,   66,   89,

       94,  111,   88,   66,   66,   98,   89,   95,   96,   66,
       92,   66,   93,   97,   99,  101,  100,   66,  126,   89,
       66,   66,  102,  105,   66,  125,  104,  127,   66,   66,
       66,   66,   66,  129,  112,  114,  109,  132,  112,  106,
       66,  128,  107,   88,  246,  112,  115,   66,  112,  178,
      112,  135,  112,   66,  130,  108,   88,  133,   66,   88,
       89,  131,  134,  137,  138,  139,   88,   88,  136,  114,
       88,   66,  166,  140,   66,  165,  140,   88,   88,  171,
      162,   66,   66,  140,  140,   66,   88,  140,  114,   88,
      142,  114,   66,   66,  140,  140,   66,   88,   88,  162,

      118,   66,  115,  140,   66,   88,  140,  163,   88,   60,
       66,  144,   66,   66,  140,  140,   88,  146,   66,  143,
       66,   88,  140,   66,   88,  140,  145,   60,   88,   66,
      147,   66,   88,  140,  149,   66,   66,   66,  140,   66,
       66,  140,   88,   66,  148,  140,   88,   66,   66,  140,
      168,   66,  164,   66,  151,  150,   66,   66,  167,  140,
      169,   66,  170,  140,  153,  152,   66,   66,  114,  154,
       88,   66,  173,   66,   66,   66,   88,  172,   66,  162,
      157,  155,   88,  156,  199,   66,   88,  140,  174,  176,
      158,   66,  200,  180,  159,   88,  175,   66,   88,  180,

       66,   66,  179,  180,   88,   88,  203,  114,  177,  182,
       66,   88,  180,   66,   88,  180,  202,   88,  115,   66,
       66,  180,  180,   88,   88,   66,   66,   66,  180,   66,
       88,  180,   66,   88,  180,  184,  183,  204,   66,   66,
      180,  180,  185,   66,   66,   66,   88,  180,   66,   88,
      180,   66,   66,   66,  188,   88,   88,   66,  189,  186,
       88,   66,   66,  180,   66,  206,  180,  190,  187,  205,
       66,   66,  180,  180,   88,   66,  114,  180,  201,  208,
      239,   88,  191,  226,   66,  192,  209,  162,  207,   66,
       88,  180,   66,   66,   88,  222,   66,  194,  210,  196,

       88,   88,   66,  225,  193,   66,   88,  210,   66,   66,
      197,  210,  195,   88,   88,   66,   66,  210,  210,  212,
       88,   66,  224,  210,   88,   88,   66,  223,   66,   66,
      210,  210,   66,   88,  204,   66,   88,  210,   66,   66,
       66,  210,  210,   88,   88,  227,   66,   88,   66,  213,
      210,   66,   88,  210,  267,   66,   88,  228,   66,   66,
      210,  210,   66,   66,  210,   88,   88,   66,  221,  210,
      215,   66,  214,  210,  241,   66,   66,   66,  229,  240,
       66,   66,  230,  230,   88,   88,  219,  247,   88,   88,
      216,  217,  232,   88,   88,  218,  220,   88,   88,   66,

       66,  230,  230,   66,   66,  230,  230,   88,   66,   66,
      230,  230,   66,   66,  230,  230,   88,   66,   66,   66,
       66,   88,   66,   66,  230,   66,   88,  198,  263,   66,
       66,   66,  234,  242,  235,  233,   66,   88,  242,  271,
      237,   66,   88,  242,  238,  236,   88,   88,  120,  120,
       88,   88,   66,  117,  242,   88,   88,   66,   66,  242,
      244,   66,   66,  242,  242,   66,   66,  242,  242,   88,
       66,   66,  248,  248,   88,  251,  111,   88,   88,  160,
       66,  250,   66,  245,   66,   88,  248,   66,   88,   66,
      121,  248,   66,   66,  252,  252,   88,  255,  118,   66,

       66,   88,  252,   66,   88,  256,  117,   88,   88,  111,
      254,   66,   88,  256,  259,   88,   66,  110,  256,   66,
       49,  260,   66,   66,  260,  260,  258,   66,   88,  264,
       66,   88,  264,   49,   88,   88,   87,  262,   88,   88,
       66,  266,   88,   66,   63,  264,   66,   88,  268,   66,
       66,  268,  268,   66,   66,  272,  272,   66,   55,  272,
       88,   88,   66,   54,  275,  270,   88,   88,   53,   51,
       88,   88,   50,  274,   88,   66,   66,  275,  275,   88,
       88,   66,   66,  277,  277,   66,   66,  279,  279,   66,
       88,  281,   49,   88,   66,   66,  281,  283,   88,   88,

       47,  311,   88,   88,  311,   66,   88,  283,   66,   88,
      285,  311,   88,   66,   66,  285,  287,   66,   66,  287,
      289,   66,   88,  289,   66,   88,  291,   66,   88,  291,
      311,   88,   88,  311,  311,   88,   88,   66,  311,  293,
       66,   88,  293,   66,   88,  295,   66,   66,  295,  297,
       66,   66,  297,  299,   88,   88,   66,  311,  299,   66,
       88,  301,  311,   88,   88,  311,  311,   88,   88,   66,
       66,  301,  303,   88,   88,   66,  311,  303,   66,   66,
      305,  305,   66,   66,  307,  307,   88,  311,   66,   66,
      309,  309,  311,  311,  311,  311,  311,  311,  311,  311,

      311,   66,  311,  309,   48,   48,   52,   52,   90,  311,
       90,  113,  113,  113,  113,  116,  116,  116,  116,  141,
      311,  141,  161,  161,  161,  161,  181,  311,  181,  211,
      311,  211,  231,  311,  231,  243,  311,  243,  249,  311,
      249,  253,  311,  253,  257,  311,  257,  261,  311,  261,
      265,  311,  265,  269,  311,  269,  273,  311,  273,  276,
      311,  276,  278,  311,  278,  280,  311,  280,  282,  311,
      282,  284,  311,  284,  286,  311,  286,  288,  311,  288,
      290,  311,  290,  292,  311,  292,  294,  311,  294,  296,
      311,  296,  298,  311,  298,  300,  311,  300,  302,  311,

      302,  304,  311,  304,  306,  311,  306,  308,  311,  308,
      310,  311,  310,    3,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311
    } ;

static yyconst short int yy_chk[1082] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,   17,   17,
       19,   19,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,   15,   16,   21,   16,   22,   15,
       25,   23,   24,   27,   30,   28,   16,   26,   34,   21,
       31,   32,   29,   68,  314,   41,   56,   60,  271,   60,
       69,  241,   60,   34,   16,   34,   23,   56,   27,   68,
       41,   24,   41,   23,   23,   25,   22,   26,   22,   23,
       24,   29,   35,   32,   26,   28,   30,   36,   31,   30,
       37,   38,   59,   70,   59,   41,   39,   35,   69,   35,
       40,   42,   36,   59,   36,   37,   38,   37,   38,   43,
       35,   39,   44,   39,   71,   40,   42,   40,   42,   46,
       73,   59,   70,   72,   43,   79,   43,   44,   74,   44,

       37,   53,   45,   75,   46,   38,   46,   37,   37,   82,
       36,   76,   36,   37,   38,   40,   39,   45,   72,   45,
       77,  138,   40,   43,   80,   71,   42,   73,   83,   81,
       84,   85,   86,   75,   53,  113,   46,   79,   53,   44,
      123,   74,   44,   89,  239,   53,  113,  124,   53,  138,
       53,   82,   53,  130,   76,   45,   90,   80,   89,   91,
       89,   77,   81,   84,   85,   86,   92,   93,   83,  114,
       94,   90,  124,   90,   91,  123,   91,   95,   96,  130,
      114,   92,   93,   92,   93,   94,   97,   94,  161,   98,
       91,  115,   95,   96,   95,   96,  229,   99,  100,  161,

      118,   97,  115,   97,   98,  101,   98,  115,  102,  118,
      126,   93,   99,  100,   99,  100,  103,   95,  128,   92,
      101,  104,  101,  102,  105,  102,   94,  118,  106,  125,
       96,  103,  107,  103,   98,  133,  104,  129,  104,  105,
      122,  105,  108,  106,   97,  106,  109,  107,  131,  107,
      126,  134,  122,  135,  100,   99,  136,  108,  125,  108,
      128,  109,  129,  109,  103,  102,  137,  139,  162,  104,
      140,  171,  133,  170,  228,  227,  141,  131,  164,  162,
      107,  105,  142,  106,  162,  140,  143,  140,  134,  136,
      108,  141,  164,  141,  109,  144,  135,  142,  145,  142,

      226,  143,  139,  143,  146,  147,  171,  163,  137,  142,
      144,  148,  144,  145,  149,  145,  170,  150,  163,  146,
      147,  146,  147,  151,  152,  175,  148,  174,  148,  149,
      153,  149,  150,  154,  150,  144,  143,  173,  151,  152,
      151,  152,  145,  173,  166,  153,  155,  153,  154,  156,
      154,  176,  177,  205,  149,  157,  158,  179,  150,  146,
      159,  155,  224,  155,  156,  175,  156,  151,  148,  174,
      157,  158,  157,  158,  180,  159,  199,  159,  166,  177,
      221,  181,  153,  205,  200,  154,  179,  199,  176,  180,
      182,  180,  202,  203,  183,  200,  181,  156,  181,  158,

      184,  185,  209,  204,  155,  182,  186,  182,  206,  183,
      159,  183,  157,  187,  188,  184,  185,  184,  185,  182,
      189,  186,  203,  186,  190,  191,  207,  202,  187,  188,
      187,  188,  223,  192,  191,  189,  193,  189,  263,  190,
      191,  190,  191,  194,  195,  206,  208,  196,  192,  184,
      192,  193,  197,  193,  263,  222,  210,  207,  194,  195,
      194,  195,  196,  201,  196,  211,  212,  197,  198,  197,
      189,  210,  188,  210,  223,  178,  172,  240,  208,  222,
      211,  212,  211,  212,  213,  214,  195,  240,  215,  216,
      192,  193,  212,  217,  218,  194,  197,  219,  220,  213,

      214,  213,  214,  215,  216,  215,  216,  230,  217,  218,
      217,  218,  219,  220,  219,  220,  231,  259,  169,  168,
      267,  232,  230,  167,  230,  165,  233,  160,  259,  132,
      127,  231,  215,  231,  216,  214,  232,  234,  232,  267,
      218,  233,  235,  233,  219,  217,  236,  237,  120,  119,
      238,  242,  234,  116,  234,  243,  244,  235,  247,  235,
      232,  236,  237,  236,  237,  238,  242,  238,  242,  245,
      243,  244,  243,  244,  248,  247,  112,  249,  250,  110,
       78,  244,  251,  233,  245,  252,  245,   67,  253,  248,
       66,  248,  249,  250,  249,  250,  254,  251,   58,  255,

      252,  256,  252,  253,  257,  253,   57,  258,  260,   52,
      250,  254,  261,  254,  255,  262,  256,   50,  256,  257,
       49,  257,  258,  260,  258,  260,  254,  261,  264,  261,
      262,  265,  262,   48,  266,  268,   33,  258,  269,  270,
       20,  262,  272,  264,   18,  264,  265,  273,  265,  266,
      268,  266,  268,  269,  270,  269,  270,  272,   14,  272,
      274,  275,  273,   13,  273,  266,  276,  277,   12,   11,
      278,  279,    9,  270,  280,  274,  275,  274,  275,  281,
      282,  276,  277,  276,  277,  278,  279,  278,  279,  280,
      283,  280,    8,  284,  281,  282,  281,  282,  285,  286,

        7,    3,  287,  288,    0,  283,  289,  283,  284,  290,
      284,    0,  291,  285,  286,  285,  286,  287,  288,  287,
      288,  289,  292,  289,  290,  293,  290,  291,  294,  291,
        0,  295,  296,    0,    0,  297,  298,  292,    0,  292,
      293,  299,  293,  294,  300,  294,  295,  296,  295,  296,
      297,  298,  297,  298,  301,  302,  299,    0,  299,  300,
      303,  300,    0,  304,  305,    0,    0,  306,  307,  301,
      302,  301,  302,  308,  309,  303,    0,  303,  304,  305,
      304,  305,  306,  307,  306,  307,  310,    0,  308,  309,
      308,  309,    0,    0,    0,    0,    0,    0,    0,    0,

        0,  310,    0,  310,  312,  312,  313,  313,  315,    0,
      315,  316,  316,  316,  316,  317,  317,  317,  317,  318,
        0,  318,  319,  319,  319,  319,  320,    0,  320,  321,
        0,  321,  322,    0,  322,  323,    0,  323,  324,    0,
      324,  325,    0,  325,  326,    0,  326,  327,    0,  327,
      328,    0,  328,  329,    0,  329,  330,    0,  330,  331,
        0,  331,  332,    0,  332,  333,    0,  333,  334,    0,
      334,  335,    0,  335,  336,    0,  336,  337,    0,  337,
      338,    0,  338,  339,    0,  339,  340,    0,  340,  341,
        0,  341,  342,    0,  342,  343,    0,  343,  344,    0,

      344,  345,    0,  345,  346,    0,  346,  347,    0,  347,
      348,    0,  348,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
#define INITIAL 0
#line 2 "compiler.l"
    #include<string.h>
    #include<stdio.h>

    #include "compiler.tab.h"
    extern void yyerror(const char *); 
    unsigned int lineno = 0;

    
#line 773 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "compiler.l"


#line 930 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 312 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1014 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 35 "compiler.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "compiler.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "compiler.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "compiler.l"
{yyerror("Unterminated Comment\n ");}
	YY_BREAK
/* Regex to truncate identifiers exceeding length 31 */
case 5:
YY_RULE_SETUP
#line 46 "compiler.l"
{   
                        yylineno ++;
                          
                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "compiler.l"
{  
                  printf("T_MAIN "); 
                  return T_MAIN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "compiler.l"
{   
                  printf("T_PRINT ");
                  return T_PRINT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "compiler.l"
{ 
                  printf("T_WHILE ");
                  return T_WHILE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 64 "compiler.l"
{ 
                  printf("T_SWITCH ");
                  return T_SWITCH; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "compiler.l"
{ 
                    
                  printf("T_DEFAULT ");
                  return T_DEFAULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "compiler.l"
{ 
                    
                  printf("T_CASE ");
                  return T_CASE; }                  
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "compiler.l"
{ 
                    
                  printf("T_IF ");
                  return T_IF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "compiler.l"
{ 
                    
                  printf("T_ELSE ");
                  return T_ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "compiler.l"
{ 
                    
                  printf("T_INCLUDE ");
                  return T_INCLUDE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "compiler.l"
{ 
                             
                          yylval.intval = T_INT;
                          printf("T_INT ");
                          return T_INT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "compiler.l"
{ 
                             
                          yylval.intval = T_DOUBLE;
                          printf("T_DOUBLE ");
                          return T_DOUBLE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "compiler.l"
{ 
                             
                          yylval.intval = T_BOOL;
                          printf("T_BOOL ");
                          return T_BOOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "compiler.l"
{ 
                             
                          yylval.intval = T_CHAR;
                          printf("T_CHAR ");
                          return T_CHAR; } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "compiler.l"
{   
                 yylval.intval = T_STRING;
                 printf("T_STRING ");
              return T_STRING;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 120 "compiler.l"
{  
              
             yylval.intval = T_VOID;
             printf("T_VOID ");
          return T_VOID; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 127 "compiler.l"
{   
             
            printf("T_RETURN ");
             return T_RETURN;
      }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "compiler.l"
{ 
                    
                  printf("T_BREAK ");
                  return T_BREAK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 137 "compiler.l"
{    
             
            printf("T_COUT ");
            return T_COUT;} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 142 "compiler.l"
{   
             
             
            printf("T_CIN ");
      return T_CIN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 148 "compiler.l"
{}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 149 "compiler.l"
{    
             
            printf("T_GE ");
      return T_GE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 154 "compiler.l"
{    
             
            printf("T_LE ");
            return T_LE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 159 "compiler.l"
{    
             
            printf("T_EQ ");
            return T_EQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 164 "compiler.l"
{    
             
            printf("T_NE ");
            return T_NE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 169 "compiler.l"
{    
             
            printf("T_OR ");
            return T_OR;
        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 175 "compiler.l"
{    
             
            printf("T_AND ");
            return T_AND;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 180 "compiler.l"
{      
             
            printf("T_INS ");
            return T_INS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 185 "compiler.l"
{      
             
            printf("T_EXT ");
            return T_EXT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 190 "compiler.l"
{      
             
            printf("T_INC ");
            return T_INC;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 194 "compiler.l"
{      
             
            printf("T_DEC ");
            return T_DEC;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 200 "compiler.l"
{    
                          return *yytext; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 204 "compiler.l"
{    
                          yylval.strval = strdup(yytext);
                          printf("T_CHAR_VAL ");
                          return T_CHAR_VAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 209 "compiler.l"
{   
                          yylval.strval = strdup(yytext);
                          printf("T_HEADER ");
                          return T_HEADER;} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 214 "compiler.l"
{ yylval.strval = strdup(yytext);
                        printf("IDENTIFIER ");
              return IDENTIFIER;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 219 "compiler.l"
{  
                            
                          yylval.strval = strdup(yytext);
                          printf("T_STRING_VAL ");
                          return T_STRING_VAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 225 "compiler.l"
{  
                       
                          yylval.strval = strdup(yytext);
                          printf("T_INTEGER_VAL ");
                          return T_INTEGER_VAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 231 "compiler.l"
{  
                            
                          yylval.strval = strdup(yytext);
                          printf("T_FLOAT_VAL ");
                          return T_FLOAT_VAL;}
	YY_BREAK
/* Regex to remove comments */
case 43:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 242 "compiler.l"
{ yyerror("Identifier length exceeded 31, truncated ");} 
	YY_BREAK
/* .                       { yyerror("Invalid character "); } */
case 44:
YY_RULE_SETUP
#line 246 "compiler.l"
ECHO;
	YY_BREAK
#line 1364 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 312 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 312 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 311);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 246 "compiler.l"
