/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 45
#define YY_END_OF_BUFFER 46
static yyconst short int yy_acclist[376] =
    {   0,
       46,   44,   45,    1,   44,   45,    5,   45,   36,   44,
       45,   36,   44,   45,   44,   45,   36,   44,   45,   36,
       44,   45,   44,   45,   36,   44,   45,   36,   44,   45,
       36,   44,   45,   41,   44,   45,   36,   44,   45,   36,
       44,   45,   36,   44,   45,   39,   44,   45,   39,   44,
       45,   39,   44,   45,   39,   44,   45,   39,   44,   45,
       39,   44,   45,   39,   44,   45,   39,   44,   45,   39,
       44,   45,   39,   44,   45,   39,   44,   45,   39,   44,
       45,   44,   45,   39,   44,   45,   39,   44,   45,   39,
       44,   45,   39,   44,   45,   39,   44,   45,   39,   44,

       45,   39,   44,   45,   39,   44,   45,   39,   44,   45,
       39,   44,   45,   39,   44,   45,   39,   44,   45,   29,
       40,   31,   34,   35,    4,    2,   41,   33,   27,   28,
       26,   32,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   12,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   30,   43,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   12,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   37,    4,    4,    2,   25,
        2,   42,   38,   39,   39,   39,   39,   24,   39,   39,
       39,   39,   39,   15,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   24,   39,
       39,   39,   39,   39,   15,   39,   39,   39,   39,   39,
       39,   39,   39,    3,    4,   17,   39,   39,   11,   39,
       18,   39,   23,   39,   39,   39,   13,   39,   39,   39,
       39,   39,   39,   20,   39,   39,   39,   39,   17,   39,
       39,   11,   39,   18,   39,   23,   39,   39,   39,   13,
       39,   39,   39,   39,   39,   39,   20,   39,   39,    3,
       42,   22,   39,   39,   39,   39,   39,   39,   39,    8,
       39,   39,   39,   22,   39,   39,   39,   39,   39,   39,
       39,    8,   39,   39,   16,   39,    6,    7,   39,   21,

       39,   19,   39,    9,   39,   39,   39,   39,   16,   39,
        7,   39,   21,   39,   19,   39,    9,   39,   10,   39,
       39,   39,   10,   39,   14,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39
    } ;

static yyconst short int yy_accept[286] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       20,   23,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   84,   87,   90,   93,   96,   99,  102,  105,
      108,  111,  114,  117,  120,  121,  121,  122,  122,  123,
      123,  123,  124,  125,  126,  127,  127,  128,  129,  130,
      131,  132,  133,  133,  134,  135,  136,  137,  138,  139,
      140,  141,  142,  143,  145,  146,  147,  148,  149,  150,
      151,  152,  153,  154,  155,  156,  157,  158,  159,  160,
      161,  162,  163,  164,  165,  166,  168,  169,  170,  171,

      172,  173,  174,  175,  176,  176,  177,  177,  178,  178,
      179,  180,  181,  182,  183,  184,  185,  186,  187,  188,
      190,  191,  192,  193,  194,  196,  197,  198,  199,  200,
      201,  202,  203,  204,  205,  206,  207,  208,  209,  211,
      212,  213,  214,  215,  217,  218,  219,  220,  221,  222,
      223,  224,  224,  224,  224,  226,  226,  228,  229,  231,
      233,  235,  236,  237,  239,  240,  241,  242,  243,  244,
      246,  247,  248,  249,  251,  252,  254,  256,  258,  259,
      260,  262,  263,  264,  265,  266,  267,  269,  270,  270,
      271,  271,  272,  274,  275,  276,  276,  277,  278,  279,

      280,  282,  283,  284,  286,  287,  288,  289,  290,  291,
      292,  294,  294,  295,  297,  298,  300,  302,  304,  306,
      307,  308,  309,  311,  313,  315,  317,  319,  319,  321,
      322,  323,  325,  326,  327,  328,  329,  330,  331,  332,
      333,  334,  335,  336,  337,  338,  339,  340,  341,  342,
      343,  344,  345,  346,  347,  348,  349,  350,  351,  352,
      353,  354,  355,  356,  357,  358,  359,  360,  361,  362,
      363,  364,  365,  366,  367,  368,  369,  370,  371,  372,
      373,  374,  375,  376,  376
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    8,   27,   27,   27,   27,   28,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       29,   30,   31,   32,   27,    8,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   44,   45,
       46,   47,   27,   48,   49,   50,   51,   52,   53,   27,
       27,   27,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    3,    4,
        3,    3,    3,    3,    3,    3,    4,    4,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[322] =
    {   0,
        0,   31,  654,  934,  934,  934,  612,  626,  590,  934,
      618,  594,  605,  585,   71,   42,   63,  575,   64,  575,
       45,   74,   76,   78,   79,   77,   80,   81,   82,   83,
       85,  535,  113,  116,  120,  134,  124,  127,  123,  155,
      156,  165,  166,  174,  934,  575,  574,  529,  934,  560,
      171,  934,  934,  136,  101,  543,   88,  934,  934,  934,
      934,  934,  520,  537,  133,  152,  139,  130,  163,  160,
      169,  173,  177,  534,  172,  179,  184,  178,  181,  186,
      192,  195,  934,  934,  214,  227,  228,  232,  235,  238,
      241,  246,  257,  260,  265,  269,  270,  276,  288,  289,

      295,  301,  307,  313,  516,  934,  530,  237,  240,  262,
      108,  934,  197,  298,  934,  219,  224,  264,  252,  511,
      249,  304,  294,  287,  510,  285,  305,  188,  314,  284,
      320,  318,  342,  346,  349,  350,  354,  355,  360,  368,
      376,  379,  382,  386,  387,  390,  408,  409,  413,  418,
      419,  482,  337,  362,  381,  400,  505,  359,  465,  461,
      430,  396,  380,  428,  137,  406,  407,  412,  416,  427,
      423,  446,  449,  450,  455,  458,  462,  468,  469,  474,
      478,  481,  482,  487,  488,  492,  501,  506,  393,  500,
      423,  420,  369,  493,  497,  346,  500,  495,  498,  504,

      329,  527,  528,  536,  539,  546,  547,  550,  555,  558,
      559,  310,  424,  326,  934,  323,  275,  180,  128,  566,
      569,  585,  588,  589,  593,  594,  597,   72,   84,  598,
      601,  607,  934,  619,  620,  623,  626,  627,  630,  631,
      639,  649,  650,  653,  657,  658,  661,  662,  669,  680,
      681,  685,  688,  689,  692,  693,  699,  711,  712,  715,
      718,  719,  722,  723,  731,  741,  742,  745,  749,  750,
      753,  754,  761,  772,  773,  777,  780,  781,  784,  785,
      791,  803,  804,  934,  822,  824,   57,  827,  831,  835,
      838,  842,  845,  848,  851,  854,  857,  860,  863,  866,

      869,  872,  875,  878,  881,  884,  887,  890,  893,  896,
      899,  902,  905,  908,  911,  914,  917,  920,  923,  926,
      929
    } ;

static yyconst short int yy_def[322] =
    {   0,
      284,    1,  284,  284,  284,  284,  284,  285,  284,  284,
      284,  286,  284,  284,  284,  284,  284,  284,  284,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  284,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  284,  285,  285,  284,  284,  284,
      284,  284,  284,  289,  290,  284,  284,  284,  284,  284,
      284,  284,  284,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  284,  284,  288,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  284,  284,  284,  289,  292,  289,
      290,  284,  290,  284,  284,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  291,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  284,  292,  292,  289,  284,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  293,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  284,  292,
      284,  284,  287,  287,  287,  284,  287,  287,  287,  287,

      287,  294,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  284,  287,  287,  284,  287,  287,  287,  287,  295,
      296,  296,  296,  296,  296,  296,  296,  284,  287,  296,
      297,  297,  284,  297,  298,  298,  299,  299,  300,  300,
      301,  301,  302,  302,  303,  303,  304,  304,  305,  305,
      306,  306,  307,  307,  308,  308,  309,  309,  310,  310,
      311,  311,  312,  312,  313,  313,  314,  314,  315,  315,
      316,  316,  317,  317,  318,  318,  319,  319,  320,  320,
      321,  321,  321,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284
    } ;

static yyconst short int yy_nxt[992] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,   11,
       12,   10,   10,   10,   13,   10,   14,   10,   15,   16,
       10,   10,   17,   18,   19,   10,   20,   20,   10,    4,
       10,   10,   20,   21,   22,   23,   24,   20,   20,   20,
       25,   20,   20,   26,   20,   20,   27,   28,   29,   20,
       20,   30,   31,   10,   32,   10,   10,   33,   33,   56,
       64,   57,   63,   33,   34,   35,   36,   37,   33,   33,
       33,   38,   33,   33,   39,   33,   33,   40,   41,   42,
       33,   33,   43,   44,   54,   58,   59,   61,   62,   55,
       65,   63,   66,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,  112,  113,   56,   67,   57,  233,   76,
      112,  113,   71,   68,   69,   84,   74,   78,   84,   70,
       73,   72,   84,   75,   82,   84,   84,   77,   81,   84,
       63,   79,   85,   63,   80,   85,   84,   63,  109,   85,
       63,   63,   85,   85,   63,   63,   85,   63,  196,  110,
       63,   63,   89,   85,   63,   98,   63,   84,   84,   90,
       91,   87,  119,   88,   96,   92,   95,   84,   84,   63,
       93,   97,   63,   63,   85,   85,   84,   63,  116,   94,
       63,  106,   63,   63,   85,   85,   63,  118,  117,   63,
       63,   63,  100,   85,   63,   63,   63,   63,   63,  112,

      113,   63,   99,   63,  107,   63,  122,  120,  107,   63,
      121,  103,   63,  104,  101,  107,   84,  102,  107,  126,
      107,  125,  107,  123,  127,  124,  130,  128,  129,   84,
       84,   63,  131,   85,   84,  132,   63,   84,  167,  109,
       84,   63,  109,   84,   63,   63,  133,  133,   84,   63,
      110,  133,   63,  154,  133,   63,  158,  133,   63,   84,
      133,  157,   84,   63,  109,  133,   63,   84,  136,   63,
      138,   84,   84,  135,   63,  110,  133,   63,   84,  133,
      155,   63,   63,  137,  133,  139,   63,   63,  133,  133,
       84,   84,   63,   63,  141,  133,  140,   84,  161,  160,

      159,   63,   63,   84,   63,   63,   63,  133,  133,   84,
      142,   63,   63,  143,  133,   84,  145,  114,   63,  144,
      133,   63,   63,  164,   63,  156,  133,  163,  146,  165,
       63,   63,  133,  169,  156,   63,  162,   63,  147,  109,
       63,  149,  148,   63,   84,  228,   63,  150,   84,  166,
      154,   84,   84,  151,  168,  170,   84,   84,  215,   63,
      171,  133,   84,   63,  109,  172,   63,   63,  172,  172,
       84,   63,   63,  172,  172,  154,   63,   63,   84,  172,
      190,   84,  175,  109,   84,   63,   63,  172,   84,   84,
      176,  174,   84,   63,  110,  172,   63,   63,  172,   63,

      193,  172,  177,   63,   63,  172,  172,   63,  179,  172,
       84,   84,  180,   63,  191,   84,  191,  178,  181,  192,
       84,   84,  195,   63,   63,   63,   63,  172,  172,   63,
       63,  182,  172,   63,  183,   63,   63,  172,  172,  192,
       63,   63,  192,  212,   63,   63,  194,   63,   84,  185,
      200,   84,   84,  187,  198,  197,  199,   84,  184,  201,
       84,  188,  186,   63,   84,  172,   63,   63,  202,  202,
       84,   84,   63,  229,  202,   63,   84,  202,   63,   63,
       84,  202,   63,   84,   84,   63,   63,  202,  202,   84,
       84,   63,  196,  202,   84,   63,  204,  202,   63,   63,

      202,  202,  109,   84,   63,   63,  202,  202,   84,   63,
       63,  202,   63,  154,   63,   63,  206,   63,   63,  205,
      202,   63,   63,   63,  189,  202,  210,   63,   63,   84,
       84,  207,  209,  214,  208,  213,  218,  216,   84,  217,
      106,   84,  211,  219,   63,   63,  202,  220,   84,   84,
      152,   63,   84,   63,   63,  220,   63,   84,  220,  115,
       84,   84,  114,   63,   63,  220,  220,   63,   84,  220,
      106,   84,   63,  105,  220,   63,   63,  220,  220,   47,
       47,  222,  223,   63,  224,  220,   63,   84,  230,   83,
       84,   84,   63,  226,  225,   84,   84,  227,   60,   84,

       84,   53,   63,   84,  230,   63,   63,  230,  230,   84,
       63,   63,  230,  230,   63,   63,  230,  230,   63,   52,
      234,   84,   84,   51,   63,   84,  234,   49,   84,   84,
       48,   47,   84,   84,  232,   45,   63,   63,  234,  236,
       63,   84,  236,   63,   63,  238,  238,   63,   63,  240,
      240,   84,   84,  284,  284,   84,   63,  284,  242,   84,
       84,  284,  284,   84,   84,  284,   63,   63,  242,  244,
       63,   84,  244,  284,   63,   63,  246,  246,   63,   63,
      248,  248,   84,   84,  284,  284,   63,   84,  250,  284,
       84,   84,  284,  284,   84,   84,  284,   63,   63,  250,

      252,   84,   63,  284,  252,   63,   63,  254,  254,   63,
       63,  256,  256,   84,   84,  284,   63,   84,  258,  284,
       84,   84,  284,  284,   84,   84,  284,  284,   63,   63,
      258,  260,   63,   84,  260,   63,   63,  262,  262,   63,
       63,  264,  264,   84,   84,  284,  284,   84,   63,  284,
      266,   84,   84,  284,  284,   84,   84,  284,   63,   63,
      266,  268,   63,   84,  268,  284,   63,   63,  270,  270,
       63,   63,  272,  272,   84,   84,  284,  284,   63,   84,
      274,  284,   84,   84,  284,  284,   84,   84,  284,   63,
       63,  274,  276,   84,   63,  284,  276,   63,   63,  278,

      278,   63,   63,  280,  280,   84,   84,  284,   63,  284,
      282,  284,  284,  284,  284,  284,  284,  284,  284,  284,
       63,   63,  282,  282,   46,   46,   50,   50,   86,  284,
       86,  108,  108,  108,  108,  111,  111,  111,  111,  134,
      284,  134,  153,  153,  153,  153,  173,  284,  173,  203,
      284,  203,  221,  284,  221,  231,  284,  231,  235,  284,
      235,  237,  284,  237,  239,  284,  239,  241,  284,  241,
      243,  284,  243,  245,  284,  245,  247,  284,  247,  249,
      284,  249,  251,  284,  251,  253,  284,  253,  255,  284,
      255,  257,  284,  257,  259,  284,  259,  261,  284,  261,

      263,  284,  263,  265,  284,  265,  267,  284,  267,  269,
      284,  269,  271,  284,  271,  273,  284,  273,  275,  284,
      275,  277,  284,  277,  279,  284,  279,  281,  284,  281,
      283,  284,  283,    3,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284

    } ;

static yyconst short int yy_chk[992] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,   16,
      287,   16,   21,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,   15,   17,   17,   19,   19,   15,
       21,   22,   21,   23,   26,   24,   25,   27,   28,   29,

       30,  229,   31,   55,   55,   57,   22,   57,  228,   26,
      111,  111,   23,   22,   22,   33,   25,   28,   34,   22,
       24,   23,   35,   25,   31,   39,   37,   27,   30,   38,
       33,   29,   33,   34,   29,   34,   36,   35,   54,   35,
       39,   37,   39,   37,   38,  219,   38,   68,  165,   54,
       65,   36,   35,   36,  165,   39,   67,   40,   41,   35,
       35,   34,   68,   34,   38,   35,   37,   42,   43,   66,
       36,   38,   40,   41,   40,   41,   44,   70,   65,   36,
       69,   51,   42,   43,   42,   43,   71,   67,   66,   75,
       72,   44,   41,   44,   73,   78,   76,  218,   79,  113,

      113,   77,   40,   80,   51,  128,   71,   69,   51,   81,
       70,   43,   82,   44,   42,   51,   85,   42,   51,   76,
       51,   75,   51,   72,   77,   73,   80,   78,   79,   86,
       87,   85,   81,   85,   88,   82,  116,   89,  128,  108,
       90,  117,  109,   91,   86,   87,   86,   87,   92,   88,
      108,   88,   89,  109,   89,   90,  117,   90,   91,   93,
       91,  116,   94,   92,  110,   92,  121,   95,   88,  119,
       90,   96,   97,   87,   93,  110,   93,   94,   98,   94,
      110,  118,   95,   89,   95,   91,   96,   97,   96,   97,
       99,  100,  217,   98,   93,   98,   92,  101,  121,  119,

      118,  130,  126,  102,  124,   99,  100,   99,  100,  103,
       94,  123,  101,   95,  101,  104,   98,  114,  102,   97,
      102,  122,  127,  124,  103,  114,  103,  123,   99,  126,
      104,  129,  104,  130,  114,  132,  122,  131,  100,  153,
      216,  102,  101,  214,  133,  212,  201,  103,  134,  127,
      153,  135,  136,  104,  129,  131,  137,  138,  196,  133,
      132,  133,  139,  134,  154,  134,  135,  136,  135,  136,
      140,  137,  138,  137,  138,  154,  158,  139,  141,  139,
      154,  142,  136,  155,  143,  140,  193,  140,  144,  145,
      137,  135,  146,  141,  155,  141,  142,  163,  142,  143,

      158,  143,  138,  144,  145,  144,  145,  146,  141,  146,
      147,  148,  142,  162,  156,  149,  156,  140,  143,  156,
      150,  151,  163,  166,  167,  147,  148,  147,  148,  168,
      149,  145,  149,  169,  146,  150,  151,  150,  151,  192,
      171,  213,  191,  189,  170,  164,  162,  161,  172,  148,
      169,  173,  174,  150,  167,  166,  168,  175,  147,  171,
      176,  151,  149,  172,  177,  172,  173,  174,  173,  174,
      178,  179,  175,  213,  175,  176,  180,  176,  160,  177,
      181,  177,  159,  182,  183,  178,  179,  178,  179,  184,
      185,  180,  182,  180,  186,  181,  175,  181,  182,  183,

      182,  183,  190,  187,  184,  185,  184,  185,  188,  186,
      194,  186,  198,  190,  195,  199,  180,  197,  187,  179,
      187,  200,  157,  188,  152,  188,  186,  125,  120,  202,
      203,  183,  185,  195,  184,  194,  199,  197,  204,  198,
      107,  205,  188,  200,  202,  203,  202,  203,  206,  207,
      105,   74,  208,  204,   64,  204,  205,  209,  205,   63,
      210,  211,   56,  206,  207,  206,  207,  208,  220,  208,
       50,  221,  209,   48,  209,  210,  211,  210,  211,   47,
       46,  205,  206,  220,  207,  220,  221,  222,  221,   32,
      223,  224,   20,  209,  208,  225,  226,  210,   18,  227,

      230,   14,  222,  231,  222,  223,  224,  223,  224,  232,
      225,  226,  225,  226,  227,  230,  227,  230,  231,   13,
      231,  234,  235,   12,  232,  236,  232,   11,  237,  238,
        9,    8,  239,  240,  222,    7,  234,  235,  234,  235,
      236,  241,  236,  237,  238,  237,  238,  239,  240,  239,
      240,  242,  243,    3,    0,  244,  241,    0,  241,  245,
      246,    0,    0,  247,  248,    0,  242,  243,  242,  243,
      244,  249,  244,    0,  245,  246,  245,  246,  247,  248,
      247,  248,  250,  251,    0,    0,  249,  252,  249,    0,
      253,  254,    0,    0,  255,  256,    0,  250,  251,  250,

      251,  257,  252,    0,  252,  253,  254,  253,  254,  255,
      256,  255,  256,  258,  259,    0,  257,  260,  257,    0,
      261,  262,    0,    0,  263,  264,    0,    0,  258,  259,
      258,  259,  260,  265,  260,  261,  262,  261,  262,  263,
      264,  263,  264,  266,  267,    0,    0,  268,  265,    0,
      265,  269,  270,    0,    0,  271,  272,    0,  266,  267,
      266,  267,  268,  273,  268,    0,  269,  270,  269,  270,
      271,  272,  271,  272,  274,  275,    0,    0,  273,  276,
      273,    0,  277,  278,    0,    0,  279,  280,    0,  274,
      275,  274,  275,  281,  276,    0,  276,  277,  278,  277,

      278,  279,  280,  279,  280,  282,  283,    0,  281,    0,
      281,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      282,  283,  282,  283,  285,  285,  286,  286,  288,    0,
      288,  289,  289,  289,  289,  290,  290,  290,  290,  291,
        0,  291,  292,  292,  292,  292,  293,    0,  293,  294,
        0,  294,  295,    0,  295,  296,    0,  296,  297,    0,
      297,  298,    0,  298,  299,    0,  299,  300,    0,  300,
      301,    0,  301,  302,    0,  302,  303,    0,  303,  304,
        0,  304,  305,    0,  305,  306,    0,  306,  307,    0,
      307,  308,    0,  308,  309,    0,  309,  310,    0,  310,

      311,    0,  311,  312,    0,  312,  313,    0,  313,  314,
        0,  314,  315,    0,  315,  316,    0,  316,  317,    0,
      317,  318,    0,  318,  319,    0,  319,  320,    0,  320,
      321,    0,  321,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
#define INITIAL 0
#line 2 "compiler.l"
    #include<string.h>
    #include<stdio.h>
    #include "compiler.tab.h"

    extern void yyerror(const char *); 

    unsigned int lineno = 0;

    #define YY_USER_ACTION yylloc.first_line = yylloc.last_line = yylineno;
    
#line 749 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "compiler.l"


#line 906 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 934 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 35 "compiler.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "compiler.l"
{ printf("comment %d\t",lineno);};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "compiler.l"
{
                          printf("comment %d\t",lineno);};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "compiler.l"
{yyerror("Unterminated Comment\n ");}
	YY_BREAK
/* Regex to truncate identifiers exceeding length 31 */
case 5:
YY_RULE_SETUP
#line 47 "compiler.l"
{
                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "compiler.l"
{ 
                  return T_MAIN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "compiler.l"
{ 
                  return T_PRINT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "compiler.l"
{ 
                  return T_WHILE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "compiler.l"
{ return T_SWITCH; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "compiler.l"
{ return T_DEFAULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "compiler.l"
{ return T_CASE; }                  
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "compiler.l"
{ return T_IF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "compiler.l"
{ return T_ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "compiler.l"
{ return T_INCLUDE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 70 "compiler.l"
{ return T_INT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "compiler.l"
{ return T_DOUBLE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 74 "compiler.l"
{ return T_BOOL; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "compiler.l"
{ return T_CHAR; } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "compiler.l"
{ return T_STRING;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "compiler.l"
{  return T_VOID; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "compiler.l"
{ return T_RETURN;
      }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "compiler.l"
{ return T_BREAK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "compiler.l"
{ return T_COUT;} 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 89 "compiler.l"
{ return T_CIN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 91 "compiler.l"
{}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "compiler.l"
{ return T_GE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 94 "compiler.l"
{ return T_LE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "compiler.l"
{ return T_EQ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "compiler.l"
{ return T_NE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "compiler.l"
{ return T_OR;
        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "compiler.l"
{ return T_AND;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 105 "compiler.l"
{ return T_INS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "compiler.l"
{ return T_EXT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 109 "compiler.l"
{ return T_INC;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 110 "compiler.l"
{ return T_DEC;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 113 "compiler.l"
{ 
                          return *yytext; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 117 "compiler.l"
{
                          yylval.strval = strdup(yytext);
                        return T_CHAR_VAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 121 "compiler.l"
{ 
                          yylval.strval = strdup(yytext);
                          return T_HEADER;} 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 "compiler.l"
{ yylval.strval = strdup(yytext);
                  return IDENTIFIER; 
              }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 130 "compiler.l"
{ 
                          yylval.strval = strdup(yytext);
                          return T_STRING_VAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "compiler.l"
{ 
                          yylval.strval = strdup(yytext);
                          return T_INTEGER_VAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 138 "compiler.l"
{                                 
                          char *c;
                          sprintf(c,"%g",atof(yytext));
                          yylval.strval = strdup(c); 
                          return T_FLOAT_VAL;}
	YY_BREAK
case 43:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 145 "compiler.l"
{  printf("Reached error\n");
                        yyerror("Identifier length exceeded 31, truncated ");} 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "compiler.l"
{ yyerror("Invalid token "); } 
	YY_BREAK
/*strcpy(yylval.strval, ^strdup(yytext){1,31}$);*/
case 45:
YY_RULE_SETUP
#line 153 "compiler.l"
ECHO;
	YY_BREAK
#line 1252 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 153 "compiler.l"
