
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[319] =
    {   0,
        0,    0,   35,   33,    4,   25,   33,   25,   25,   33,
       25,   29,   25,   25,   25,   27,   27,   27,   31,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   33,   27,
       27,   27,   31,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   22,    0,   28,   24,    0,    0,    3,    0,
       29,   20,   21,   19,    0,   27,   31,   27,   31,   27,
       27,   27,   27,   27,   27,    7,   27,   27,   27,   27,
       27,   23,   32,   27,   27,   31,   27,   31,   31,   27,
       27,   27,   27,   27,   27,    7,   27,   27,   27,   27,
       27,   26,    0,    3,    3,   30,   27,   27,   31,   27,

       27,   18,   27,   27,   27,   27,   10,   27,   27,   27,
       27,   27,   27,   31,   31,   27,   31,   27,   27,   18,
       27,   27,   27,   27,   10,   27,   27,   27,   27,    2,
        0,   27,   31,   12,   13,   17,   27,    8,   27,    5,
       27,   27,   15,   27,   27,   31,   31,   27,   31,   12,
       13,   17,   27,    8,   27,    5,   27,   27,   15,    0,
       30,   27,   31,   27,   27,   27,   27,   27,   27,   31,
       31,   27,   31,   27,   27,   27,   27,   27,   31,   11,
       27,   16,   14,   27,   27,   31,   31,   27,   31,   11,
       27,   16,   14,   31,    6,    9,   27,   27,   31,   31,

       31,    6,    9,   31,   27,   27,   31,   31,   31,   31,
       27,   27,   31,   31,   31,   31,   27,   27,   31,   31,
       31,   31,   27,   27,   31,   31,   31,   31,   27,   27,
       31,   31,   31,   31,   27,   27,   31,   31,   31,    1,
       27,   27,   31,   31,    1,   27,   27,   31,   31,   27,
       27,   31,   31,   27,   27,   31,   31,   27,   27,   31,
       31,   27,   27,   31,   31,   27,   27,   31,   31,   27,
       27,   31,   31,   27,   27,   31,   31,   27,   27,   31,
       31,   27,   27,   31,   31,   27,   27,   31,   31,   27,
       27,   31,   31,   27,   27,   31,   31,   27,   27,   31,

       31,   27,   27,   31,   31,   27,   27,   31,   31,   27,
       27,   31,   31,   27,   27,   31,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    3,    3,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,    3,   24,   24,   25,   24,   26,   24,
       27,   28,   29,   24,   24,   30,   31,   32,   33,   24,
       24,   24,   34,   35,   24,   24,   36,   24,   24,   24,
       37,   38,   39,   40,   41,    3,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   24,   24,   51,   52,   53,
       54,   24,   24,   55,   56,   57,   58,   59,   24,   24,
       24,   24,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    4,    3,    5,    3,    3,    3,
        3,    3,    3,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    3,    3,    3,    3,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    3,
        3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[386] =
    {   0,
        0,   63,  488, 1409, 1409,  465,  480, 1409,  475,  427,
      446,  112,  431,  430,  426,  113,  115,  116,    0,  117,
      118,  119,  123,  122,  120,  124,  125,  135,  372,  175,
      176,  179,  134,  182,  183,   92,   98,  154,  160,  172,
      181,  190, 1409,  425,  417, 1409,  387,  198,  376,  369,
      128, 1409, 1409, 1409,  333,  138,    0,  227,  321,  171,
      219,  213,  228,  231,  232,  172,  233,  234,  235,  241,
      237, 1409, 1409,  213,  268,  178,  278,  262,  289,  297,
      298,  301,  305,  306,  309,  315,  326,  343,  351,  357,
      360, 1409,  340,  333,  172,  335, 1409,  358,  308,  286,

      314,  256,  356,  290,  361,  363,  364,  365,  374,  375,
      376,  394,  421,  332,  386,  422,  417,  425,  426,  429,
      454,  457,  458,  462,  476,  490,  495,  499,  506,  324,
      436,  453,  296,  379,  385,  414,  439,  443,  474,  446,
      487,  481,  494,  522,  531,  524,  527,  543,  548,  552,
      553,  559,  564,  573,  580,  581,  584,  587,  601,  287,
      285,  565,  264,  595,  572,  570,  523,  617,  618,  590,
      607,  628,  627,  635,  645,  646,  653,  515,  255,  537,
      631,  612,  634,  663,  680,  649,  654,  681,  662,  690,
      691,  698,  701,  240,    0,  669,  709,  710,  672,  700,

      718,  712,  721,  225,  731,  732,  728,  738,  742,  198,
      739,  750,  751,  759,  761,  196,  762,  767,  764,  768,
      769,  193,  772,  781,  788,  792,  793,  183,  797,  800,
      799,  804,  816,  176,  809,  825,  818,  826,  827,    0,
      830,  834,  829,  835,  837,  853,  857,  856,  859,  862,
      863,  865,  867,  884,  885,  879,  888,  891,  895,  890,
      907,  912,  913,  914,  916,  920,  932,  921,  938,  941,
      942,  943,  946,  949,  950,  960,  967,  970,  977,  969,
      972,  978,  986,  979,  995,  998, 1005,  997, 1000, 1006,
     1014, 1007, 1008, 1026, 1033, 1028, 1032, 1036, 1042, 1035,

     1052, 1056, 1061, 1058, 1062, 1070, 1078, 1064, 1082, 1086,
     1089, 1088, 1090, 1098, 1106, 1092, 1108, 1409, 1145, 1148,
     1150,  150, 1154, 1158, 1163, 1167, 1171, 1175, 1179, 1183,
     1187, 1191, 1195, 1199, 1203, 1207, 1211, 1215, 1219, 1223,
     1227, 1231, 1235, 1239, 1243, 1247, 1251, 1255, 1259, 1263,
     1267, 1271, 1275, 1279, 1283, 1287, 1291, 1295, 1299, 1303,
     1307, 1311, 1315, 1319, 1323, 1327, 1331, 1335, 1339, 1343,
     1347, 1351, 1355, 1359, 1363, 1367, 1371, 1375, 1379, 1383,
     1387, 1391, 1395, 1399, 1403
    } ;

static yyconst flex_int16_t yy_def[386] =
    {   0,
      318,  318,  318,  318,  318,  318,  319,  318,  318,  320,
      318,  318,  318,  318,  318,  321,  321,  321,  322,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  318,  323,
      323,  323,  324,  323,  323,   35,   35,   35,   35,   35,
       35,   35,  318,  319,  319,  318,  318,  318,  325,  318,
      318,  318,  318,  318,  318,  321,  322,  321,  322,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  318,  318,   35,  326,  327,  326,  327,  324,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  318,  318,  325,  325,  318,  318,  321,  322,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  326,  328,  329,  327,  328,  329,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  325,
      318,  321,  322,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  328,  330,  331,  329,  330,  331,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  318,
      318,  321,  322,  321,  321,  321,  321,  330,  332,  333,
      331,  332,  333,  332,  332,  332,  332,  321,  322,  321,
      321,  321,  321,  332,  334,  335,  333,  334,  335,  334,
      334,  334,  334,  322,  322,  321,  334,  336,  337,  335,

      337,  337,  336,  322,  336,  338,  339,  337,  339,  322,
      338,  340,  341,  339,  341,  322,  340,  342,  343,  341,
      343,  322,  342,  344,  345,  343,  345,  322,  344,  346,
      347,  345,  347,  322,  346,  348,  349,  347,  349,  322,
      348,  350,  351,  349,  351,  350,  352,  353,  351,  352,
      354,  355,  353,  354,  356,  357,  355,  356,  358,  359,
      357,  358,  360,  361,  359,  360,  362,  363,  361,  362,
      364,  365,  363,  364,  366,  367,  365,  366,  368,  369,
      367,  368,  370,  371,  369,  370,  372,  373,  371,  372,
      374,  375,  373,  374,  376,  377,  375,  376,  378,  379,

      377,  378,  380,  381,  379,  380,  382,  383,  381,  382,
      384,  385,  383,  384,  384,  385,  385,    0,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318
    } ;

static yyconst flex_int16_t yy_nxt[1473] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,    8,    8,
        8,    8,    8,    8,    8,   11,   12,    8,    8,   13,
       14,   15,    8,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   17,   18,   16,    8,    4,    8,    8,
       19,   16,   20,   21,   22,   23,   16,   16,   16,   24,
       16,   25,   16,   16,   26,   27,   16,   16,   28,    8,
       29,    8,    8,    4,    5,    4,    6,    7,    8,    9,
       10,    8,    8,    8,    8,    8,    8,    8,   11,   12,
        8,    8,   13,   14,   15,    8,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   31,   32,   30,    8,

        4,    8,    8,   33,   30,   34,   35,   36,   37,   30,
       30,   30,   38,   30,   39,   30,   30,   40,   41,   30,
       30,   42,    8,   29,    8,    8,   50,   55,   51,   55,
       55,   55,   55,   55,   55,   73,   55,   55,   55,   55,
       75,   75,   50,   58,   51,   84,   75,   75,   85,   55,
       79,   75,   55,   57,   57,   57,   59,   57,   57,   57,
       57,   68,   57,   57,   57,   57,   61,   62,   66,   69,
       60,   63,   64,   65,   67,   57,   73,   73,   57,   73,
       73,   70,   95,   73,   73,   55,   55,  130,   71,   55,
       55,   74,   74,   55,  115,   74,   55,   55,   74,   74,

       86,   88,   75,   75,   77,   92,   87,   75,   75,   75,
      240,   57,   57,   75,  234,   76,   76,   89,  228,   78,
       75,   75,   76,   76,  100,   75,  222,   55,  216,   75,
       75,   81,   82,   55,   75,   80,   83,   90,   75,   75,
       93,   55,   55,   91,   93,   55,   55,   55,   55,   55,
       93,   55,   93,   57,   93,   55,   93,  210,   98,   57,
      101,   75,   75,   73,  204,  102,   75,   57,   57,   73,
       55,   57,   57,   57,   57,   57,  106,   57,  115,   73,
      195,   57,   55,  108,  112,  103,  111,  105,  104,  107,
       73,  109,   55,  179,  112,  110,   57,  117,   73,   73,

       55,  161,   73,  161,   55,   79,   73,   73,  114,  116,
       73,   55,   55,  112,  112,   55,   73,  112,  114,   55,
       55,  112,  112,   55,  163,  112,   57,   73,   55,   55,
       57,  112,  137,   73,   95,  133,  134,  114,  114,  119,
       55,  114,  112,   95,   73,  114,  114,   92,  147,  114,
      118,   96,   73,  120,   57,  114,   99,   55,   73,  112,
      131,   73,  121,  122,  123,   55,  114,  112,  135,  124,
       55,   55,   55,  112,   55,   55,  112,   55,   55,   55,
      131,   97,  125,  114,  132,   96,   95,   73,   55,   55,
       55,  114,  126,   55,   92,   73,   57,  114,   57,   55,

      114,   57,  115,   57,   57,   57,  138,  127,   55,  129,
      112,  128,  136,  139,   57,   57,   57,  140,   73,   57,
      143,   45,   73,   73,  142,   57,   73,   73,   55,   45,
       73,  141,   72,  147,  114,   55,   55,  144,  144,   55,
       55,  144,  144,   55,  149,  144,   54,  160,  148,  160,
       53,   52,  161,   55,   57,   73,   49,   55,   73,   73,
       55,  146,  146,   73,   48,  146,  146,   55,   55,  146,
      144,   55,   55,  144,  144,  150,   55,   73,  144,   57,
      151,   46,  162,   57,   45,   43,   57,  318,   55,  164,
       55,   73,  144,   57,  146,   55,   73,  146,  146,  153,

       73,   55,  146,  154,   55,  318,  144,   73,   55,   55,
      152,  144,  155,   55,   57,  144,  146,  318,  318,  318,
       55,   57,  144,   73,  318,   73,  318,   57,   73,   55,
      146,  165,   73,  167,   57,  146,   55,   55,  144,  146,
      171,  166,  156,  147,   73,   55,  146,  168,  158,   73,
      159,   55,  157,   73,   73,  194,  318,   55,  318,  168,
       73,  318,  146,   57,  171,   73,   55,   55,  168,  168,
      183,  170,  172,   55,   73,  168,  173,   57,   55,   55,
      168,   73,   73,  170,   55,   73,   55,   55,   73,  168,
      178,   73,  170,  170,   55,   55,  168,  168,   55,  170,

      168,   55,   73,  168,  170,   57,  187,  318,   73,   55,
       57,  318,   57,  170,  174,   55,  181,  168,   73,   73,
      170,  170,  182,  171,  170,  318,   55,  170,   73,   73,
      318,   55,   55,  168,  184,   57,   73,  175,  176,  177,
      180,  170,   55,  187,  184,   55,   73,   73,   55,   55,
       73,  184,   57,  188,   73,   73,  189,  170,  186,   55,
       55,  184,  184,   73,   73,  200,  318,   55,  186,  184,
      187,   57,  318,   73,   57,  186,  196,   55,  200,  184,
      190,   73,   73,   55,  318,  186,  186,  202,  208,  191,
      318,   73,   73,  186,   55,   55,  197,  197,  192,   73,

      193,   73,   73,  186,   55,   55,  197,  197,  318,   57,
       73,   73,   55,   73,  197,   55,  200,  197,  318,   73,
      199,  201,   73,   55,   55,  197,  205,  318,  208,   73,
      199,  199,   73,   73,  208,   55,  203,  205,  199,   73,
       73,  199,  209,   73,  214,   55,   55,  205,  211,  199,
      207,   73,   73,   55,  208,  211,  318,  318,  214,  318,
       73,  207,   73,   73,   55,   73,  217,  220,   73,   73,
       73,  207,  213,   73,  215,  214,   55,  220,  217,  213,
      226,   55,   73,  223,  220,  226,   55,  318,  223,   73,
      219,  221,  318,   73,   73,   55,  318,  229,   73,  227,

       73,   73,  219,  318,  232,   73,  318,  225,  226,  232,
       73,   55,  225,  229,   55,  238,  235,   73,  233,   73,
      232,  231,  318,   55,  318,  235,   73,   73,   73,  318,
       73,   73,  238,  318,  244,   73,   73,  231,   73,   55,
      237,  241,  238,  244,   55,  249,  241,  239,   55,  237,
      246,  244,  318,  249,   73,  318,  318,   73,   73,  318,
       73,  245,  318,   73,   73,  243,   73,   55,   73,  246,
      243,   55,  253,  250,  248,  249,   55,   55,  250,  254,
       73,  257,  318,  253,  318,   73,   73,  318,  318,   73,
      318,   73,   73,  248,  318,  261,   73,  252,   55,   55,

      254,  258,  252,  256,  257,   55,  265,  258,   73,   55,
      318,  262,  318,   73,   73,   73,  318,   73,  318,  318,
      318,   73,   73,  261,  256,  260,   55,   55,  262,  266,
      269,  260,  265,   73,   55,  264,  266,  273,  318,   73,
      318,  318,   73,   73,   73,  318,   55,   73,  270,  318,
       73,   73,  264,  268,  269,   55,   55,  270,  274,  277,
      268,   73,  273,   55,   55,  274,  278,  318,   73,  318,
       73,   73,  272,   73,  318,  318,  281,  318,   73,   73,
       73,  272,  276,  277,   55,  285,  278,   73,  281,  276,
      280,   55,   55,  282,  282,  289,   73,  318,   73,   73,

       55,   73,  286,  318,  318,  318,   73,   73,   73,   73,
      280,  285,   55,  293,  286,   73,  289,  284,  284,   55,
       55,  290,  290,  297,  293,  318,  288,   73,   55,   73,
      294,  318,  318,   73,   73,  318,   73,   73,  288,  318,
       55,  318,  294,   73,  301,  292,  292,   55,  297,  298,
       55,  305,  298,   73,  296,  318,   55,   73,  302,   73,
      318,  318,   73,   73,  318,   73,  296,  318,  301,  318,
       55,   73,  302,  300,  309,   55,  300,  306,  305,   73,
      313,  318,  304,   73,   55,  318,  306,   73,  318,   73,
       73,   73,   55,   73,  310,  318,  304,  318,  309,   73,

       55,  308,  310,   55,  317,  314,  313,   73,  317,   73,
      308,  318,   55,  318,  314,  318,  318,  318,  312,  318,
       55,  318,  314,  318,  317,  318,  312,  318,  318,  316,
      318,  318,  318,  318,  318,  318,  318,  318,  316,  318,
      318,  318,  318,  318,  318,  318,  316,   44,   44,   44,
       47,   47,   47,   56,   56,   75,  318,   75,   75,   76,
      318,  318,   76,   94,  318,   94,   94,   94,  113,  318,
      113,  113,  114,  318,  318,  114,  145,  318,  145,  145,
      146,  318,  318,  146,  169,  318,  169,  169,  170,  318,
      318,  170,  185,  318,  185,  185,  186,  318,  318,  186,

      198,  318,  198,  198,  199,  318,  318,  199,  206,  318,
      206,  206,  207,  318,  318,  207,  212,  318,  212,  212,
      213,  318,  318,  213,  218,  318,  218,  218,  219,  318,
      318,  219,  224,  318,  224,  224,  225,  318,  318,  225,
      230,  318,  230,  230,  231,  318,  318,  231,  236,  318,
      236,  236,  237,  318,  318,  237,  242,  318,  242,  242,
      243,  318,  318,  243,  247,  318,  247,  247,  248,  318,
      318,  248,  251,  318,  251,  251,  252,  318,  318,  252,
      255,  318,  255,  255,  256,  318,  318,  256,  259,  318,
      259,  259,  260,  318,  318,  260,  263,  318,  263,  263,

      264,  318,  318,  264,  267,  318,  267,  267,  268,  318,
      318,  268,  271,  318,  271,  271,  272,  318,  318,  272,
      275,  318,  275,  275,  276,  318,  318,  276,  279,  318,
      279,  279,  280,  318,  318,  280,  283,  318,  283,  283,
      284,  318,  318,  284,  287,  318,  287,  287,  288,  318,
      318,  288,  291,  318,  291,  291,  292,  318,  318,  292,
      295,  318,  295,  295,  296,  318,  318,  296,  299,  318,
      299,  299,  300,  318,  318,  300,  303,  318,  303,  303,
      304,  318,  318,  304,  307,  318,  307,  307,  308,  318,
      318,  308,  311,  318,  311,  311,  312,  318,  318,  312,

      315,  318,  315,  315,  316,  318,  318,  316,    3,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318
    } ;

static yyconst flex_int16_t yy_chk[1473] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,   12,   16,   12,   17,
       18,   20,   21,   22,   25,   33,   24,   23,   26,   27,
       36,   36,   51,   17,   51,   36,   37,   37,   37,   28,
       33,   37,   56,   16,  322,   17,   18,   20,   21,   22,
       25,   25,   24,   23,   26,   27,   21,   21,   24,   26,
       20,   21,   22,   23,   24,   28,   30,   31,   56,   76,
       32,   27,   95,   34,   35,   60,   66,   95,   28,   30,
       31,   30,   31,   32,   76,   32,   34,   35,   34,   35,

       38,   39,   38,   38,   31,   48,   38,   38,   39,   39,
      234,   60,   66,   39,  228,   30,   31,   40,  222,   32,
       40,   40,   34,   35,   60,   40,  216,   62,  210,   41,
       41,   35,   35,   61,   41,   34,   35,   41,   42,   42,
       48,   58,   63,   42,   48,   64,   65,   67,   68,   69,
       48,   71,   48,   62,   48,   70,   48,  204,   58,   61,
       61,   74,   74,   78,  194,   62,   74,   58,   63,   75,
      102,   64,   65,   67,   68,   69,   67,   71,   78,   77,
      179,   70,   75,   68,   75,   63,   71,   65,   64,   67,
       79,   69,   77,  163,   77,   70,  102,   78,   80,   81,

      100,  161,   82,  160,  104,   79,   83,   84,   75,   77,
       85,   80,   81,   80,   81,   82,   86,   82,   77,   83,
       84,   83,   84,   85,  133,   85,  100,   87,  101,   86,
      104,   86,  104,  114,  130,   99,  100,   80,   81,   81,
       87,   82,   87,   94,   88,   83,   84,   93,  114,   85,
       80,   96,   89,   82,  101,   86,   59,   88,   90,   88,
       96,   91,   83,   84,   85,   89,   87,   89,  101,   87,
      103,   90,   98,   90,   91,  105,   91,  106,  107,  108,
       96,   55,   87,   88,   98,   50,   49,  115,  109,  110,
      111,   89,   88,  134,   47,  112,  103,   90,   98,  135,

       91,  105,  115,  106,  107,  108,  105,   89,  112,   91,
      112,   90,  103,  106,  109,  110,  111,  108,  117,  134,
      111,   45,  113,  116,  110,  135,  118,  119,  136,   44,
      120,  109,   29,  117,  112,  113,  116,  113,  116,  118,
      119,  118,  119,  120,  117,  120,   15,  131,  116,  131,
       14,   13,  131,  137,  136,  121,   11,  138,  122,  123,
      140,  113,  116,  124,   10,  118,  119,  132,  121,  120,
      121,  122,  123,  122,  123,  118,  124,  125,  124,  137,
      119,    9,  132,  138,    7,    6,  140,    3,  139,  137,
      125,  126,  125,  132,  121,  142,  127,  122,  123,  122,

      128,  141,  124,  123,  126,    0,  126,  129,  143,  127,
      121,  127,  124,  128,  139,  128,  125,    0,    0,    0,
      129,  142,  129,  144,    0,  146,    0,  141,  147,  178,
      126,  139,  145,  142,  143,  127,  144,  167,  144,  128,
      146,  141,  126,  147,  148,  145,  129,  145,  128,  149,
      129,  180,  127,  150,  151,  178,    0,  148,    0,  148,
      152,    0,  144,  167,  149,  153,  150,  151,  150,  151,
      167,  145,  148,  152,  154,  152,  149,  180,  153,  162,
      153,  155,  156,  148,  166,  157,  165,  154,  158,  154,
      162,  170,  150,  151,  155,  156,  155,  156,  157,  152,

      157,  158,  159,  158,  153,  162,  170,    0,  171,  164,
      166,    0,  165,  154,  153,  159,  165,  159,  168,  169,
      155,  156,  166,  171,  157,    0,  182,  158,  173,  172,
        0,  168,  169,  168,  169,  164,  174,  155,  157,  158,
      164,  159,  172,  173,  172,  181,  175,  176,  183,  174,
      186,  174,  182,  172,  177,  187,  173,  168,  169,  175,
      176,  175,  176,  189,  184,  186,    0,  177,  172,  177,
      187,  181,    0,  199,  183,  174,  181,  184,  189,  184,
      174,  185,  188,  196,    0,  175,  176,  189,  199,  175,
        0,  190,  191,  177,  185,  188,  185,  188,  176,  192,

      177,  200,  193,  184,  190,  191,  190,  191,    0,  196,
      197,  198,  192,  202,  192,  193,  200,  193,    0,  201,
      185,  188,  203,  197,  198,  197,  198,    0,  202,  207,
      190,  191,  205,  206,  201,  203,  191,  203,  192,  208,
      211,  193,  201,  209,  207,  205,  206,  205,  206,  197,
      198,  212,  213,  211,  208,  211,    0,    0,  209,    0,
      214,  203,  215,  217,  212,  219,  212,  213,  218,  220,
      221,  205,  206,  223,  209,  214,  217,  215,  217,  211,
      219,  218,  224,  218,  220,  221,  223,    0,  223,  225,
      212,  215,    0,  226,  227,  224,    0,  224,  229,  221,

      231,  230,  217,    0,  225,  232,    0,  218,  226,  227,
      235,  229,  223,  229,  230,  231,  230,  233,  227,  237,
      232,  224,    0,  235,    0,  235,  236,  238,  239,    0,
      243,  241,  233,    0,  237,  242,  244,  229,  245,  236,
      230,  236,  238,  239,  241,  243,  241,  233,  242,  235,
      242,  244,    0,  245,  246,    0,    0,  248,  247,    0,
      249,  239,    0,  250,  251,  236,  252,  246,  253,  246,
      241,  247,  248,  247,  242,  249,  250,  251,  250,  251,
      256,  252,    0,  253,    0,  254,  255,    0,    0,  257,
        0,  260,  258,  246,    0,  256,  259,  247,  254,  255,

      254,  255,  250,  251,  257,  258,  260,  258,  261,  259,
        0,  259,    0,  262,  263,  264,    0,  265,    0,    0,
        0,  266,  268,  261,  254,  255,  262,  263,  262,  263,
      264,  258,  265,  267,  266,  259,  266,  268,    0,  269,
        0,    0,  270,  271,  272,    0,  267,  273,  267,    0,
      274,  275,  262,  263,  269,  270,  271,  270,  271,  272,
      266,  276,  273,  274,  275,  274,  275,    0,  277,    0,
      280,  278,  267,  281,    0,    0,  276,    0,  279,  282,
      284,  270,  271,  277,  278,  280,  278,  283,  281,  274,
      275,  279,  282,  279,  282,  284,  285,    0,  288,  286,

      283,  289,  283,    0,    0,    0,  287,  290,  292,  293,
      278,  285,  286,  288,  286,  291,  289,  279,  282,  287,
      290,  287,  290,  292,  293,    0,  283,  294,  291,  296,
      291,    0,    0,  297,  295,    0,  300,  298,  286,    0,
      294,    0,  294,  299,  296,  287,  290,  295,  297,  295,
      298,  300,  298,  301,  291,    0,  299,  302,  299,  304,
        0,    0,  303,  305,    0,  308,  294,    0,  301,    0,
      302,  306,  302,  295,  304,  303,  298,  303,  305,  307,
      308,    0,  299,  309,  306,    0,  306,  310,    0,  312,
      311,  313,  307,  316,  307,    0,  302,    0,  309,  314,

      310,  303,  310,  311,  312,  311,  313,  315,  316,  317,
      306,    0,  314,    0,  314,    0,    0,    0,  307,    0,
      315,    0,  315,    0,  317,    0,  310,    0,    0,  311,
        0,    0,    0,    0,    0,    0,    0,    0,  314,    0,
        0,    0,    0,    0,    0,    0,  315,  319,  319,  319,
      320,  320,  320,  321,  321,  323,    0,  323,  323,  324,
        0,    0,  324,  325,    0,  325,  325,  325,  326,    0,
      326,  326,  327,    0,    0,  327,  328,    0,  328,  328,
      329,    0,    0,  329,  330,    0,  330,  330,  331,    0,
        0,  331,  332,    0,  332,  332,  333,    0,    0,  333,

      334,    0,  334,  334,  335,    0,    0,  335,  336,    0,
      336,  336,  337,    0,    0,  337,  338,    0,  338,  338,
      339,    0,    0,  339,  340,    0,  340,  340,  341,    0,
        0,  341,  342,    0,  342,  342,  343,    0,    0,  343,
      344,    0,  344,  344,  345,    0,    0,  345,  346,    0,
      346,  346,  347,    0,    0,  347,  348,    0,  348,  348,
      349,    0,    0,  349,  350,    0,  350,  350,  351,    0,
        0,  351,  352,    0,  352,  352,  353,    0,    0,  353,
      354,    0,  354,  354,  355,    0,    0,  355,  356,    0,
      356,  356,  357,    0,    0,  357,  358,    0,  358,  358,

      359,    0,    0,  359,  360,    0,  360,  360,  361,    0,
        0,  361,  362,    0,  362,  362,  363,    0,    0,  363,
      364,    0,  364,  364,  365,    0,    0,  365,  366,    0,
      366,  366,  367,    0,    0,  367,  368,    0,  368,  368,
      369,    0,    0,  369,  370,    0,  370,  370,  371,    0,
        0,  371,  372,    0,  372,  372,  373,    0,    0,  373,
      374,    0,  374,  374,  375,    0,    0,  375,  376,    0,
      376,  376,  377,    0,    0,  377,  378,    0,  378,  378,
      379,    0,    0,  379,  380,    0,  380,  380,  381,    0,
        0,  381,  382,    0,  382,  382,  383,    0,    0,  383,

      384,    0,  384,  384,  385,    0,    0,  385,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
    #include<string.h>
    #include<stdio.h>
    #include "y.tab.h"

    int yylval;
    void yyerror(char *);
	unsigned int lineno = 0;

    extern YYLTYPE yyloc;
    #define YY_USER_INIT yylloc.first_line = 1;
    
#line 906 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 34 "lex.l"



#line 1095 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 319 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1409 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "lex.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "lex.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "lex.l"
{yyerror("Unterminated Comment\n");}
	YY_BREAK
/* Regex to truncate identifiers exceeding length 31 */
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 46 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column = 0; 
                          yyloc.first_line = lineno++;
                          return T_NEWLINE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                  yylloc.first_column = ++yylloc.last_column; 
                  yylloc.last_column += yyleng - 1; 
                  return T_MAIN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "lex.l"
{ 
                  yylloc.first_line = yylloc.last_line;
                  yylloc.first_column = ++yylloc.last_column; 
                  yylloc.last_column += yyleng - 1; 
                  return T_T_WHILE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "lex.l"
{ 
                  yylloc.first_line = yylloc.last_line;
                  yylloc.first_column = ++yylloc.last_column; 
                  yylloc.last_column += yyleng - 1; 
                  return T_IF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "lex.l"
{ 
                  yylloc.first_line = yylloc.last_line;
                  yylloc.first_column = ++yylloc.last_column; 
                  yylloc.last_column += yyleng - 1; 
                  return T_ELSE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 76 "lex.l"
{ 
                  yylloc.first_line = yylloc.last_line;
                  yylloc.first_column = ++yylloc.last_column; 
                  yylloc.last_column += yyleng - 1; 
                  return T_INCLUDE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "lex.l"
{ 
                          yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1; 
                          return T_INT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 88 "lex.l"
{ 
                          yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1; 
                          return T_DOUBLE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "lex.l"
{ 
                          yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1; 
                          return T_BOOL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "lex.l"
{ 
                          yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1; 
                          return T_CHAR; } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "lex.l"
{ 	
              yylloc.first_line = yylloc.last_line;
            	yylloc.first_column = ++yylloc.last_column;
           	  yylloc.last_column += yyleng -1; 
           	  return T_STRING;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "lex.l"
{ 	
          yylloc.first_line = yylloc.last_line;
          yylloc.first_column = ++yylloc.last_column;
         	yylloc.last_column += yyleng -1; 
         	return T_VOID; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "lex.l"
{  yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
      		   return T_RETURN;
	    }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 125 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
            return T_COUT;} 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 130 "lex.l"
{   
            yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
			return T_CIN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 136 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
			return T_GE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 141 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
            return T_LE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
            return T__EQ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 151 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
            return T_NE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 156 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
            return T__OR;
        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 162 "lex.l"
{   yylloc.first_line = yylloc.last_line;
            yylloc.first_column = ++yylloc.last_column;
            yylloc.last_column += yyleng -1;
            return T__AND;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 168 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1; 
                          return atoi(*yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 174 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1; 
                          yylval.CHAR = *yytext;
                          return T_CHAR_VAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 180 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column;
                          yylloc.last_column += yyleng -1;
                          char *s = (char*)malloc(sizeof(char)*(strlen(yytext)+1));
                          strcpy(s,yytext);
                          yylval.STR = s;
                          return T_HEADER;} 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column; 
                          yylloc.last_column += yyleng - 1; 
                          char *s = (char*)malloc(sizeof(char)*(strlen(yytext)+1));
                          strcpy(s,yytext);
                            yylval.STR= s;
                          return T_STRING_VAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 197 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                     yylloc.first_column = ++yylloc.last_column; 
                          yylloc.last_column += yyleng - 1; 
                          yylval.INT = atoi(*yytext);
                          return T_INTEGER_VAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 203 "lex.l"
{ yylloc.first_line = yylloc.last_line;
                          yylloc.first_column = ++yylloc.last_column; 
                          yylloc.last_column += yyleng - 1; 
                          yylval.FLOAT = atof(*yytext);
                          return T_FLOAT_VAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 211 "lex.l"
{ char *s = (char*)malloc(sizeof(char)*(strlen(yytext)+1));
                          strcpy(s,yytext);
						  yylval.STR= s;
						  return T_IDENTIFIER;}
	YY_BREAK
/* Regex to remove comments */
case 32:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 217 "lex.l"
{ yyerror("Identifier length exceeded 31, truncated");} 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 219 "lex.l"
{ yyerror("Invalid character"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 221 "lex.l"
ECHO;
	YY_BREAK
#line 1463 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 319 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 319 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 318);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 221 "lex.l"



int main(){
    yylex();
    return 0;
}
